### ISSUE TITLE
ValueError: Error: Unexpected observation shape (1, 12) for Box environment, please use (1, 15) or (n_env, 1, 15) for the observation shape.

### ISSUE THREAD

**Issue by Fenxues** [WangZY233/FR5_Reinforcement-learning#1]
运行Fr5_test.py时有报错：ValueError: Error: Unexpected observation shape (1, 12) for Box environment, please use (1, 15) or (n_env, 1, 15) for the observation shape.

**Comment by WangZY233** [comment]
是的 那个模型文件不对应的 你需要重新训练

---- Replied Message ----
| From | Wang ***@***.***> |
| Date | 05/08/2024 09:33 |
| To | WangZY233/FR5_Reinforcement-learning ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [WangZY233/FR5_Reinforcement-learning] ValueError: Error: Unexpected observation shape (1, 12) for Box environment, please use (1, 15) or (n_env, 1, 15) for the observation shape. (Issue #1) |

运行Fr5_test.py时有报错：ValueError: Error: Unexpected observation shape (1, 12) for Box environment, please use (1, 15) or (n_env, 1, 15) for the observation shape.
是不是模型文件best_model_1.5mm和env不对应的原因？

**Comment by WangZY233** [comment]
已在提交cf9c1fa中修改了这个错误

**Comment by Fenxues** [comment]
谢谢。修改后的项目已在本地成功运行并测试了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WangZY233/FR5_Reinforcement-learning"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月9日(星期四) 下午4:20
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [WangZY233/FR5_Reinforcement-learning] ValueError: Error: Unexpected observation shape (1, 12) for Box environment, please use (1, 15) or (n_env, 1, 15) for the observation shape. (Issue #1)





 
已在提交cf9c1fa中修改了这个错误
